# Generated by Django 4.2.7 on 2025-02-06 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterreg',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='voters/'),
        ),
        migrations.AddField(
            model_name='voterreg',
            name='voter_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
