# Generated by Django 4.2.7 on 2025-01-26 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibleVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(default=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.voterreg')),
            ],
        ),
    ]
