# Generated by Django 4.2.7 on 2025-01-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Not Available', 'Not Available'), ('Available', 'Available')], max_length=20)),
            ],
        ),
    ]
