# Generated by Django 4.2.7 on 2025-02-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterreg',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voterreg',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
