# Generated by Django 4.2.7 on 2025-02-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_voterreg_fullname_alter_voterreg_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterreg',
            old_name='is_verified',
            new_name='verified',
        ),
    ]
