# Generated by Django 4.2.7 on 2025-01-26 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_eligiblevoter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligiblevoter',
            name='is_eligible',
        ),
        migrations.AddField(
            model_name='eligiblevoter',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eligiblevoter',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_voters', to='vote.election'),
        ),
    ]
