# Generated by Django 4.2.7 on 2025-01-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_remove_eligiblevoter_is_eligible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligiblevoter',
            name='voter',
        ),
    ]
